// @generated by examples/generate_typed_builtins.rs. Do not edit.
// The adjacent catalog.pb owns every semantic field; indices are locations only.

#[doc = "A protobuf-owned symbolic i64 value. Structural equality preserves exact literal payloads.\n\n"]
#[derive(
    ::core::clone::Clone,
    ::core::fmt::Debug,
    ::core::cmp::PartialEq,
    ::core::cmp::Eq,
    ::core::hash::Hash,
)]
pub struct I64(crate::typed::expr::Expr);
impl crate::typed::expr::ValueInput for self::I64 {
    type Owned = Self;
}
impl ::core::convert::From<&self::I64> for self::I64 {
    fn from(__egglog_value: &self::I64) -> Self {
        ::core::clone::Clone::clone(__egglog_value)
    }
}
impl crate::typed::EgglogValue for self::I64 {
    fn sort_ref() -> crate::typed::SortRef {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Sort;
        __egglog_record.index = 1;
        crate::typed::SortRef(__egglog_record)
    }
    fn expression(&self) -> &crate::typed::expr::Expr {
        &self.0
    }
    fn from_expression(__egglog_value: crate::typed::expr::Expr) -> Self {
        Self(__egglog_value)
    }
}
impl ::core::convert::From<::core::primitive::i64> for self::I64 {
    fn from(__egglog_value: ::core::primitive::i64) -> Self {
        Self(
            crate::typed::expr::Expr::literal(
                <Self as crate::typed::EgglogValue>::sort_ref(),
                crate::typed::pb::PrimitiveValue {
                    value: ::core::option::Option::Some(
                        crate::typed::pb::primitive_value::Value::I64(__egglog_value),
                    ),
                },
            )
            .expect("generated scalar codec and catalog sort disagree"),
        )
    }
}
impl ::core::convert::From<&::core::primitive::i64> for self::I64 {
    fn from(__egglog_value: &::core::primitive::i64) -> Self {
        let __egglog_value = *__egglog_value;
        Self(
            crate::typed::expr::Expr::literal(
                <Self as crate::typed::EgglogValue>::sort_ref(),
                crate::typed::pb::PrimitiveValue {
                    value: ::core::option::Option::Some(
                        crate::typed::pb::primitive_value::Value::I64(__egglog_value),
                    ),
                },
            )
            .expect("generated scalar codec and catalog sort disagree"),
        )
    }
}
impl ::core::convert::TryFrom<&self::I64> for ::core::primitive::i64 {
    type Error = crate::typed::TypedError;
    fn try_from(__egglog_value: &self::I64) -> ::core::result::Result<Self, Self::Error> {
        let __egglog_record = &__egglog_value.0.0;
        let __egglog_node = &__egglog_record.owner.as_ref().unwrap().program.nodes
            [__egglog_record.index as ::core::primitive::usize];
        if crate::typed::SortRef(
            __egglog_record.resolve(crate::typed::storage::Arena::Sort, __egglog_node.sort_id)?,
        ) != <self::I64 as crate::typed::EgglogValue>::sort_ref()
        {
            return ::core::result::Result::Err(crate::typed::TypedError::Decode(
                ::std::borrow::ToOwned::to_owned("literal wrapper has another sort"),
            ));
        }
        match &__egglog_node.kind {
            ::core::option::Option::Some(crate::typed::pb::node::Kind::PrimitiveValue(
                crate::typed::pb::PrimitiveValue {
                    value:
                        ::core::option::Option::Some(crate::typed::pb::primitive_value::Value::I64(
                            __egglog_value,
                        )),
                },
            )) => ::core::result::Result::Ok(*__egglog_value),
            _ => ::core::result::Result::Err(crate::typed::TypedError::Decode(
                ::std::borrow::ToOwned::to_owned(
                    "expected an exact ::core::primitive::i64 literal, not symbolic syntax",
                ),
            )),
        }
    }
}

#[doc = "A protobuf-owned symbolic f64 value. Structural equality preserves exact literal payloads.\n\n"]
#[derive(
    ::core::clone::Clone,
    ::core::fmt::Debug,
    ::core::cmp::PartialEq,
    ::core::cmp::Eq,
    ::core::hash::Hash,
)]
pub struct F64(crate::typed::expr::Expr);
impl crate::typed::expr::ValueInput for self::F64 {
    type Owned = Self;
}
impl ::core::convert::From<&self::F64> for self::F64 {
    fn from(__egglog_value: &self::F64) -> Self {
        ::core::clone::Clone::clone(__egglog_value)
    }
}
impl crate::typed::EgglogValue for self::F64 {
    fn sort_ref() -> crate::typed::SortRef {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Sort;
        __egglog_record.index = 0;
        crate::typed::SortRef(__egglog_record)
    }
    fn expression(&self) -> &crate::typed::expr::Expr {
        &self.0
    }
    fn from_expression(__egglog_value: crate::typed::expr::Expr) -> Self {
        Self(__egglog_value)
    }
}
impl ::core::convert::From<::core::primitive::f64> for self::F64 {
    fn from(__egglog_value: ::core::primitive::f64) -> Self {
        Self(
            crate::typed::expr::Expr::literal(
                <Self as crate::typed::EgglogValue>::sort_ref(),
                crate::typed::pb::PrimitiveValue {
                    value: ::core::option::Option::Some(
                        crate::typed::pb::primitive_value::Value::F64Bits(__egglog_value.to_bits()),
                    ),
                },
            )
            .expect("generated scalar codec and catalog sort disagree"),
        )
    }
}
impl ::core::convert::From<&::core::primitive::f64> for self::F64 {
    fn from(__egglog_value: &::core::primitive::f64) -> Self {
        let __egglog_value = *__egglog_value;
        Self(
            crate::typed::expr::Expr::literal(
                <Self as crate::typed::EgglogValue>::sort_ref(),
                crate::typed::pb::PrimitiveValue {
                    value: ::core::option::Option::Some(
                        crate::typed::pb::primitive_value::Value::F64Bits(__egglog_value.to_bits()),
                    ),
                },
            )
            .expect("generated scalar codec and catalog sort disagree"),
        )
    }
}
impl ::core::convert::TryFrom<&self::F64> for ::core::primitive::f64 {
    type Error = crate::typed::TypedError;
    fn try_from(__egglog_value: &self::F64) -> ::core::result::Result<Self, Self::Error> {
        let __egglog_record = &__egglog_value.0.0;
        let __egglog_node = &__egglog_record.owner.as_ref().unwrap().program.nodes
            [__egglog_record.index as ::core::primitive::usize];
        if crate::typed::SortRef(
            __egglog_record.resolve(crate::typed::storage::Arena::Sort, __egglog_node.sort_id)?,
        ) != <self::F64 as crate::typed::EgglogValue>::sort_ref()
        {
            return ::core::result::Result::Err(crate::typed::TypedError::Decode(
                ::std::borrow::ToOwned::to_owned("literal wrapper has another sort"),
            ));
        }
        match &__egglog_node.kind {
            ::core::option::Option::Some(crate::typed::pb::node::Kind::PrimitiveValue(
                crate::typed::pb::PrimitiveValue {
                    value:
                        ::core::option::Option::Some(crate::typed::pb::primitive_value::Value::F64Bits(
                            __egglog_value,
                        )),
                },
            )) => ::core::result::Result::Ok(::core::primitive::f64::from_bits(*__egglog_value)),
            _ => ::core::result::Result::Err(crate::typed::TypedError::Decode(
                ::std::borrow::ToOwned::to_owned(
                    "expected an exact ::core::primitive::f64 literal, not symbolic syntax",
                ),
            )),
        }
    }
}

/// A protobuf-owned ordered vector expression. Native calls remain symbolic.
#[derive(
    ::core::clone::Clone,
    ::core::fmt::Debug,
    ::core::cmp::PartialEq,
    ::core::cmp::Eq,
    ::core::hash::Hash,
)]
pub struct Vec<__EgglogType0: crate::typed::EgglogValue>(
    crate::typed::expr::Expr,
    ::core::marker::PhantomData<fn() -> __EgglogType0>,
);
impl<__EgglogType0: crate::typed::EgglogValue> crate::typed::expr::ValueInput
    for self::Vec<__EgglogType0>
{
    type Owned = Self;
}
impl<__EgglogType0: crate::typed::EgglogValue> ::core::convert::From<&self::Vec<__EgglogType0>>
    for self::Vec<__EgglogType0>
{
    fn from(__egglog_value: &Self) -> Self {
        ::core::clone::Clone::clone(__egglog_value)
    }
}
impl<__EgglogType0: crate::typed::EgglogValue> crate::typed::EgglogValue
    for self::Vec<__EgglogType0>
{
    fn sort_ref() -> crate::typed::SortRef {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 2;
        crate::typed::SortRef::family(
            &__egglog_record,
            ::std::vec![<__EgglogType0 as crate::typed::EgglogValue>::sort_ref()],
        )
        .expect("generated family arity")
    }
    fn expression(&self) -> &crate::typed::expr::Expr {
        &self.0
    }
    fn from_expression(__egglog_value: crate::typed::expr::Expr) -> Self {
        Self(__egglog_value, ::core::marker::PhantomData)
    }
}
impl<__EgglogType0: crate::typed::EgglogValue> ::core::convert::TryFrom<&self::Vec<__EgglogType0>>
    for ::std::vec::Vec<__EgglogType0>
{
    type Error = crate::typed::TypedError;
    fn try_from(
        __egglog_value: &self::Vec<__EgglogType0>,
    ) -> ::core::result::Result<Self, Self::Error> {
        let mut __egglog_items = ::std::vec::Vec::new();
        for __egglog_child in __egglog_value
            .0
            .vec_elements(&<__EgglogType0 as crate::typed::EgglogValue>::sort_ref())?
        {
            __egglog_items.push(
                <__EgglogType0 as crate::typed::EgglogValue>::from_expression(__egglog_child),
            );
        }
        ::core::result::Result::Ok(__egglog_items)
    }
}

impl ::core::ops::Add<self::F64> for self::F64 {
    type Output = self::F64;
    fn add(self, __egglog_rhs: self::F64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 4;
        <self::F64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<&self::F64> for self::F64 {
    type Output = self::F64;
    fn add(self, __egglog_rhs: &self::F64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 4;
        <self::F64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<self::F64> for &self::F64 {
    type Output = self::F64;
    fn add(self, __egglog_rhs: self::F64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 4;
        <self::F64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<&self::F64> for &self::F64 {
    type Output = self::F64;
    fn add(self, __egglog_rhs: &self::F64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 4;
        <self::F64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<self::I64> for self::I64 {
    type Output = self::I64;
    fn add(self, __egglog_rhs: self::I64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 5;
        <self::I64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<&self::I64> for self::I64 {
    type Output = self::I64;
    fn add(self, __egglog_rhs: &self::I64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 5;
        <self::I64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<self::I64> for &self::I64 {
    type Output = self::I64;
    fn add(self, __egglog_rhs: self::I64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 5;
        <self::I64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl ::core::ops::Add<&self::I64> for &self::I64 {
    type Output = self::I64;
    fn add(self, __egglog_rhs: &self::I64) -> Self::Output {
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 5;
        <self::I64 as crate::typed::EgglogValue>::from_expression(crate::typed::expr::Expr::call(
            &crate::typed::decl::Callable(__egglog_record),
            ::std::vec![
                ::core::clone::Clone::clone(&self.0),
                ::core::clone::Clone::clone(&__egglog_rhs.0)
            ],
        ))
    }
}

impl<__EgglogType0: crate::typed::EgglogValue> self::Vec<__EgglogType0> {
    /// Author a catalog-defined call without evaluating its arguments.
    pub fn empty() -> self::Vec<__EgglogType0> {
        let __egglog_args = ::std::vec![];

        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 9;
        <self::Vec<__EgglogType0> as crate::typed::EgglogValue>::from_expression(
            crate::typed::expr::Expr::call_with_result(
                &crate::typed::decl::Callable(__egglog_record),
                __egglog_args,
                <self::Vec<__EgglogType0> as crate::typed::EgglogValue>::sort_ref(),
            )
            .expect("generated generic call disagrees with its descriptor"),
        )
    }
}

impl<__EgglogType0: crate::typed::EgglogValue> self::Vec<__EgglogType0> {
    /// Author a catalog-defined call without evaluating its arguments.
    pub fn get(&self, __egglog_arg_0: impl ::core::convert::Into<self::I64>) -> __EgglogType0 {
        let __egglog_args = ::std::vec![::core::clone::Clone::clone(&self.0), {
            let __egglog_value: self::I64 = ::core::convert::Into::into(__egglog_arg_0);
            ::core::clone::Clone::clone(<self::I64 as crate::typed::EgglogValue>::expression(
                &__egglog_value,
            ))
        }];

        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 10;
        <__EgglogType0 as crate::typed::EgglogValue>::from_expression(
            crate::typed::expr::Expr::call_with_result(
                &crate::typed::decl::Callable(__egglog_record),
                __egglog_args,
                <__EgglogType0 as crate::typed::EgglogValue>::sort_ref(),
            )
            .expect("generated generic call disagrees with its descriptor"),
        )
    }
}

impl<__EgglogType0: crate::typed::EgglogValue> self::Vec<__EgglogType0> {
    /// Author a catalog-defined call without evaluating its arguments.
    pub fn of(
        __egglog_arg_0: impl ::core::iter::IntoIterator<
            Item = impl ::core::convert::Into<__EgglogType0>,
        >,
    ) -> self::Vec<__EgglogType0> {
        let mut __egglog_args = ::std::vec![];
        for __egglog_value in ::core::iter::IntoIterator::into_iter(__egglog_arg_0) {
            let __egglog_value: __EgglogType0 = ::core::convert::Into::into(__egglog_value);
            __egglog_args.push(::core::clone::Clone::clone(
                <__EgglogType0 as crate::typed::EgglogValue>::expression(&__egglog_value),
            ));
        }
        let mut __egglog_record =
            ::core::clone::Clone::clone(crate::typed::storage::builtin_catalog());
        __egglog_record.arena = crate::typed::storage::Arena::Declaration;
        __egglog_record.index = 11;
        <self::Vec<__EgglogType0> as crate::typed::EgglogValue>::from_expression(
            crate::typed::expr::Expr::call_with_result(
                &crate::typed::decl::Callable(__egglog_record),
                __egglog_args,
                <self::Vec<__EgglogType0> as crate::typed::EgglogValue>::sort_ref(),
            )
            .expect("generated generic call disagrees with its descriptor"),
        )
    }
}
